---
- name: Deploy static website to web servers
  hosts: webservers
  become: yes
  gather_facts: yes

  vars:
    web_root: /var/www/html

  pre_tasks:
    - name: Set web service and user/group for Debian/Ubuntu
      ansible.builtin.set_fact:
        web_service: apache2
        web_user: www-data
        web_group: www-data
      when: ansible_os_family == "Debian"

    - name: Set web service and user/group for RHEL/Amazon
      ansible.builtin.set_fact:
        web_service: httpd
        web_user: apache
        web_group: apache
      when: ansible_os_family == "RedHat" or ansible_distribution == "Amazon"

  tasks:

    - name: Ensure Apache is installed (Ubuntu/Debian)
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Ensure Apache (httpd) is installed (Amazon/RHEL)
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat" or ansible_distribution == "Amazon"

    # ✅ ADDED: Start Apache service (minimal change)
    - name: Ensure Apache service is running
      ansible.builtin.service:
        name: "{{ web_service }}"
        state: started
        enabled: yes

    - name: Ensure document root exists
      ansible.builtin.file:
        path: "{{ web_root }}"
        state: directory
        owner: "{{ web_user }}"
        group: "{{ web_group }}"
        mode: "0755"

    - name: Copy website files (HTML + images)
      ansible.builtin.copy:
        src: "web-src/"
        dest: "{{ web_root }}/"
        owner: "{{ web_user }}"
        group: "{{ web_group }}"
        mode: "0644"
        directory_mode: "0755"
      notify: Restart web server

    - name: Restore SELinux context on web root (RHEL/Amazon only)
      ansible.builtin.command: "restorecon -Rvv {{ web_root }}"
      when: ansible_os_family == "RedHat" or ansible_distribution == "Amazon"
      changed_when: false
      failed_when: false

  handlers:
    - name: Restart web server
      ansible.builtin.service:
        name: "{{ web_service }}"
        state: restarted
